@echo off
mkdir src
mkdir src\app
mkdir src\components
mkdir src\components\ui
mkdir src\components\atoms
mkdir src\components\molecules
mkdir src\components\organisms
mkdir src\components\templates
mkdir src\app\api
mkdir src\app\api\trpc
mkdir "src\app\api\trpc\[trpc]"
mkdir "src\app\(auth)"
mkdir "src\app\(auth)\login"
mkdir "src\app\(auth)\register"
mkdir src\app\dashboard
mkdir "src\app\dashboard\[scanId]"
mkdir src\server
mkdir src\server\api
mkdir src\server\scan
mkdir src\server\queue
mkdir src\server\storage
mkdir src\lib
mkdir src\lib\utils
mkdir src\lib\firebase